window.WIREFRAME = {
  meta: {
    title: "ws-email-agent",
    subtitle: "Email Agent · responsibility queue mockup source",
    source: "screens-brief.md",
    styleRef: "design-system-tokens.css · OpenClaw Design System",
    avatar: "✉️"
  },
  tabs: [
    { id: "s1", label: "Kết nối Gmail" },
    { id: "s2", label: "Việc cần xử lý" },
    { id: "s3", label: "Soạn follow-up" },
    { id: "s4", label: "Cài đặt nhắc" }
  ],
  screens: {
    s1: {
      states: [
        { id: "first", label: "first-run · chưa nối" },
        { id: "loading", label: "loading · OAuth + scan" },
        { id: "error", label: "error · thiếu scope" },
        { id: "done", label: "done → S2.first-run" }
      ],
      html: {
        first: `
          <style>.hero{max-width:980px;margin:12px auto 0;display:grid;grid-template-columns:1.1fr .9fr;gap:14px;align-items:stretch}.heroTitle{font-size:34px;line-height:1.05;letter-spacing:-.04em;margin:0 0 10px}.scopeList{display:grid;gap:8px}.scopeItem{display:flex;gap:10px;padding:10px 12px;border:.5px solid var(--border);border-radius:12px;background:var(--card-2)}.scopeItem b:first-child{width:18px}.dataUse{margin-top:14px}.riskGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.riskBox{padding:10px;border:.5px solid var(--border);border-radius:12px;background:var(--card-2)}.fieldgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.fieldbox{padding:8px;border:.5px solid var(--border);border-radius:10px;background:var(--card-2)}.fieldbox span{display:block;font-size:11px;color:var(--ink-3);font-family:var(--mono)}.thread{border:.5px solid var(--border);border-radius:12px;background:var(--card);padding:12px;margin-bottom:8px}.thread.hot{box-shadow:inset 3px 0 0 var(--bad)}.thread.warn{box-shadow:inset 3px 0 0 var(--warn)}.thread.ok{box-shadow:inset 3px 0 0 var(--ok)}.thread.info{box-shadow:inset 3px 0 0 var(--info)}.evidence{background:var(--card-2);border:.5px solid var(--border);border-radius:12px;padding:10px;margin-top:8px}.mask{font-family:var(--mono);font-size:12px;color:var(--ink-2)}@media(max-width:850px){.hero,.grid2{grid-template-columns:1fr}.riskGrid,.fieldgrid,.grid3{grid-template-columns:1fr 1fr}}</style>
          <div class="hero">
            <div class="card">
              <span class="pill p-blue">draft + approve · không tự gửi</span>
              <h1 class="heroTitle">Kết nối Gmail để agent tìm phần trách nhiệm còn lại trong inbox.</h1>
              <p class="muted">Cấp quyền tối thiểu để agent đọc inbox và soạn follow-up, không tự gửi. Agent đọc email để làm nhiệm vụ trong workspace của anh, không dùng email để train/fine-tune model dùng chung.</p>
              <div class="gap"></div>
              <button class="btn pri big">Kết nối Gmail</button>
              <div class="note">Retention 90 ngày · purge khi disconnect · thu hồi quyền bất kỳ lúc nào.</div>
            </div>
            <div class="card">
              <h3>Quyền truy cập</h3>
              <div class="scopeList">
                <div class="scopeItem"><b>✓</b><div><b>Đọc thread</b><div class="small muted">Phân loại awaiting / replied / bounced / safe wait.</div></div></div>
                <div class="scopeItem"><b>✓</b><div><b>Soạn draft</b><div class="small muted">Tạo bản nháp follow-up để anh duyệt.</div></div></div>
                <div class="scopeItem"><b>✕</b><div><b>Không auto-send</b><div class="small muted">Gửi mail luôn cần anh bấm duyệt.</div></div></div>
              </div>
              <div class="dataUse"><h3>Cách dùng dữ liệu</h3><div class="scopeList"><div class="scopeItem"><b>✓</b><div><b>Đọc email để làm nhiệm vụ</b><div class="small muted">Không giấu việc này: agent cần đọc thread để tìm trách nhiệm còn lại.</div></div></div><div class="scopeItem"><b>✕</b><div><b>Không train/fine-tune model dùng chung</b><div class="small muted">Email của anh không dùng để train bất kỳ model chung nào.</div></div></div><div class="scopeItem"><b>✓</b><div><b>Thu hồi & xoá theo yêu cầu</b><div class="small muted">Lưu tối đa 90 ngày · xóa khi ngắt kết nối.</div></div></div></div></div>
            </div>
          </div>`,
        loading: `
          <div class="card" style="max-width:760px;margin:40px auto">
            <h2 class="t">Đang quét lịch sử & học giọng</h2>
            <p class="muted">OAuth đã xong. Agent đang dựng hàng đợi lần đầu, học giọng/cadence ban đầu và chuẩn bị S2.first-run.</p>
            <div class="progbar"><i style="width:68%"></i></div>
            <div class="step"><span class="mk">✓</span><span class="lb">Đã kết nối Gmail</span><span class="pill p-ok">xong</span></div>
            <div class="step"><span class="mk">✓</span><span class="lb">Đã phân loại 80 thread gần nhất</span><span class="pill p-ok">xong</span></div>
            <div class="step"><span class="mk">◌</span><span class="lb">Đang học giọng viết từ mail đã gửi</span><span class="pill p-blue">đang chạy</span></div>
            <div class="step"><span class="mk">◌</span><span class="lb">Đang ước lượng cadence nhắc phù hợp</span><span class="pill p-warn">đang chạy</span></div>
            <div class="locked">Bằng chứng mặc định sẽ là pattern + subject được mask nhẹ (mức B). Full thread (mức C) chỉ mở khi anh bấm xem sâu.</div>
          </div>`,
        error: `<div class="modalbox"><div class="mh">Không đủ quyền Gmail <span>⚠️</span></div><div class="mb"><p>Agent chưa thể đọc thread để phân loại trách nhiệm hôm nay.</p><div class="locked">Cần quyền đọc thread và tạo draft. Không yêu cầu quyền auto-send.</div></div><div class="mf"><button class="btn">Để sau</button><button class="btn pri">Thử lại</button></div></div>`,
        done: `<div class="empty"><div class="big">✅</div><b>Đã kết nối Gmail</b><div class="muted small">Đi tiếp tới S2.first-run để xem agent dựng hàng đợi lần đầu.</div><div class="gap"></div><button class="btn pri">Mở Việc cần xử lý</button></div>`
      }
    },
    s2: {
      states: [
        { id: "done", label: "done · 9 decisions" },
        { id: "why", label: "Vì sao nổi?" },
        { id: "memory", label: "memory-suggestion-present" },
        { id: "allSafe", label: "all-safe" },
        { id: "firstRun", label: "first-run" },
        { id: "loading", label: "loading" },
        { id: "error", label: "error" }
      ],
      html: {
        done: `
          <style>.command{display:grid;grid-template-columns:1fr 320px;gap:14px}.digest{font-size:28px;letter-spacing:-.03em;line-height:1.08;margin:0}.bucket{margin-top:12px}.bucket h3{justify-content:space-between}.num{font-size:20px}.trace{display:grid;gap:8px}.trace div{padding:9px 10px;border:.5px solid var(--border);border-radius:12px;background:var(--card-2)}.miniTable{display:grid;gap:7px}.miniTable .between{padding:8px 0;border-bottom:.5px solid var(--border)}.chiprow{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}@media(max-width:900px){.command{grid-template-columns:1fr}}</style>
          <div class="command"><div>
            <div class="card"><div class="between"><span class="pill p-ok">Agent đã lọc inbox</span><button class="btn soft">Xem coverage</button></div><h1 class="digest">80 email đã xử lý · 9 việc cần anh xử lý hôm nay.</h1><p class="muted">Đây không phải inbox. Đây là phần trách nhiệm còn lại sau khi agent đã phân loại, theo dõi và bỏ qua an toàn phần còn lại.</p><div class="gap"></div><div class="trace" style="grid-template-columns:repeat(3,1fr);display:grid"><div><b>Phân loại</b><div class="small muted">80 thread đã đọc & gán loại</div></div><div><b>Quản lý</b><div class="small muted">24 thread đang sống, chờ an toàn</div></div><div><b>Điều phối</b><div class="small muted">9 việc cần anh xử hôm nay</div></div></div></div>
            <div class="card bucket"><h3>Mail bị trả lại <span class="num">1</span></h3><div class="thread hot"><div class="between"><b>Proposal gửi cho acme*** bị bounce</b><span class="pill p-bad">pipeline dead-end</span></div><div class="small muted">Pipeline đang kẹt vì mail không tới · cần sửa địa chỉ hoặc gửi lại để deal không chết im.</div><div class="fieldgrid"><div class="fieldbox"><span>waiting_on</span>delivery failed</div><div class="fieldbox"><span>aging</span>hôm nay</div><div class="fieldbox"><span>confidence</span>high</div><div class="fieldbox"><span>next_action_hint</span>Sửa địa chỉ / gửi lại</div></div><div class="mask">Detect → Surface · last_meaningful_snippet: Delivery has failed to these recipients...</div><div class="gap"></div><button class="btn pri">Mở thread</button> <button class="btn">Vì sao nổi?</button></div></div>
            <div class="card bucket"><h3>Cần bạn trả lời <span class="num">3</span></h3><div class="thread warn"><div class="between"><b>Lan hỏi chiết khấu năm, chưa chốt</b><span class="pill p-warn">money + commitment</span></div><div class="small muted">Bạn đang giữ bóng · reply có ask mới, agent không nên đóng thay anh · chờ đối tác 0 ngày · confidence cao.</div><div class="fieldgrid"><div class="fieldbox"><span>waiting_on</span>you</div><div class="fieldbox"><span>value_type</span>money</div><div class="fieldbox"><span>suggested_next_date</span>hôm nay</div><div class="fieldbox"><span>next_action_hint</span>Mở Gmail để trả lời</div></div><div class="mask">Surface → Human decision · “confirm giúp em giá cuối và ngày bắt đầu?”</div><div class="gap"></div><button class="btn pri">Mở Gmail để trả lời</button> <button class="btn">Hẹn lại</button> <button class="btn ghost">Vì sao nổi?</button></div><div class="thread warn"><div class="between"><b>Meeting prep cho demo chiều nay</b><span class="pill p-warn">meeting &lt;48h</span></div><div class="small muted">Bạn đang giữ bóng · có tài liệu cần xem trước meeting trong 48h.</div></div></div>
            <div class="card bucket"><h3>Đã có reply <span class="num">2</span></h3><div class="thread ok"><div class="between"><b>Đối tác đã xác nhận nhận proposal</b><span class="pill p-ok">suggest close</span></div><div class="small muted">Agent đề xuất đóng, cần anh xác nhận · không có ask mới.</div><div class="fieldgrid"><div class="fieldbox"><span>waiting_on</span>closed candidate</div><div class="fieldbox"><span>value_type</span>commitment</div><div class="fieldbox"><span>confidence</span>high</div><div class="fieldbox"><span>next_action_hint</span>Xác nhận đóng</div></div><div class="mask">Track reply → Closed/Snoozed · “Received, thanks.”</div><div class="gap"></div><button class="btn pri">Xác nhận đóng</button> <button class="btn">Chưa phải reply</button></div></div>
            <div class="card bucket"><h3>Cần follow-up <span class="num">3</span></h3><div class="thread info"><div class="between"><b>Proposal gửi 5 ngày chưa reply</b><span class="pill p-blue">draft ready · money</span></div><div class="small muted">Chờ đối tác 5 ngày · draft follow-up sẵn · confidence cao · Duyệt để gửi.</div><div class="fieldgrid"><div class="fieldbox"><span>waiting_on</span>them</div><div class="fieldbox"><span>last_user_sent_at</span>5 ngày trước</div><div class="fieldbox"><span>suggested_next_date</span>hôm nay</div><div class="fieldbox"><span>next_action_hint</span>Duyệt draft</div></div><div class="mask">Draft ready → Track reply · last_meaningful_snippet: Em gửi proposal bản cập nhật...</div><div class="gap"></div><button class="btn pri">Mở thread</button> <button class="btn">Hẹn lại</button> <button class="btn">Bỏ qua</button> <button class="btn ghost">Vì sao nổi?</button></div><div class="locked">Có thể bỏ qua · <b>71</b> thread deprioritized đã thu gọn: newsletter, FYI, auto-ack, tracking chưa tới hạn. (KHÔNG tính vào 9 việc cần quyết.)</div></div>
          </div><aside class="card"><h3>Agent work trace</h3><div class="trace"><div>✓ Đã scan 80 email mới</div><div>✓ Đã check deal/payment/order</div><div>✓ Đã check commitment/promises</div><div>✓ Đã check meeting trong 48h</div><div>✓ Đã check bounced/failed delivery</div></div><div class="gap"></div><div class="suggest"><b>Operating Memory</b><div class="small muted">Em thấy anh thường ưu tiên money risk trước reputation risk.</div><button class="btn soft" style="margin-top:8px">Xem đề xuất</button></div></aside></div>`,
        why: `<div class="grid2"><div class="card"><h2 class="t">Vì sao thread này nổi?</h2><div class="thread hot"><b>Proposal gửi cho acme*** bị bounce</b><div class="small muted">last_meaningful_message: proposal + quote sent · waiting_on: nobody · NDR báo không giao được.</div></div><div class="evidence"><b>Signals</b><div class="miniTable"><div class="between"><span>value_type</span><span class="pill p-bad">money</span></div><div class="between"><span>risk</span><span class="pill p-bad">pipeline blocked</span></div><div class="between"><span>confidence</span><span class="pill p-ok">high</span></div><div class="between"><span>next_action_hint</span><span>Sửa địa chỉ / gửi lại</span></div><div class="between"><span>loop</span><span>Detect → Surface</span></div></div></div></div><div class="card"><h3>Coverage phía sau summary</h3><div class="miniTable"><div class="between"><span>Spam/newsletter/system</span><b>31</b></div><div class="between"><span>FYI / no action</span><b>18</b></div><div class="between"><span>Waiting safely</span><b>9</b></div><div class="between"><span>Already handled</span><b>6</b></div><div class="between"><span>Tracking but not due</span><b>7</b></div></div><div class="note">Mục này tạo trust cho claim “80 email processed → 9 decisions left”.</div></div></div>`,
        memory: `<div class="card" style="max-width:960px;margin:auto"><div class="between"><b>Agent học được 2 pattern từ cách anh xử lý tuần này</b><button class="btn soft">Xem đề xuất</button></div><div class="chiprow"><span class="pill p-blue">Anh thường bỏ qua thread FYI một lần</span><span class="pill p-blue">Khách ACME nên ưu tiên cao hơn</span></div><div class="note">Chỉ surface để anh biết; agent KHÔNG tự áp rule tại đây — mở S4 “Cài đặt nhắc” để xác nhận từng đề xuất.</div></div><div class="card bucket" style="max-width:960px;margin:12px auto"><h3>Cần follow-up <span class="num">3</span></h3><div class="thread info"><div class="between"><b>Proposal gửi 5 ngày chưa reply</b><span class="pill p-blue">draft ready</span></div><div class="small muted">Chờ đối tác 5 ngày · draft follow-up sẵn, cần anh duyệt.</div><div class="gap"></div><button class="btn pri">Mở thread</button> <button class="btn">Bỏ qua</button></div></div>`,
        allSafe: `<div class="empty"><div class="big">✅</div><b>Không có việc cần anh xử lý</b><div class="muted small">Agent vẫn đang theo dõi 24 thread; 8 thread đang chờ an toàn, 16 thread chưa tới hạn. Không có thread rủi ro cao bị bỏ quên.</div><div class="gap"></div><button class="btn soft">Xem coverage</button></div>`,
        firstRun: `<div class="card" style="max-width:760px;margin:24px auto"><h2 class="t">Đang dựng hàng đợi lần đầu</h2><p class="muted">Agent đang phân loại inbox và học giọng + cadence ban đầu của anh. Lần đầu có thể mất vài phút.</p><div class="progbar"><i style="width:52%"></i></div><div class="step"><span class="mk">✓</span><span class="lb">Đã phân loại 80 thread gần nhất</span><span class="pill p-ok">xong</span></div><div class="step"><span class="mk">◌</span><span class="lb">Đang học giọng viết từ mail đã gửi</span><span class="pill p-blue">đang chạy</span></div><div class="step"><span class="mk">◌</span><span class="lb">Đang ước lượng cadence nhắc phù hợp</span><span class="pill p-warn">đang chạy</span></div></div>`,
        loading: `<div class="card"><h2 class="t">Đang phân loại & điều phối</h2><div class="progbar"><i style="width:42%"></i></div><div class="grid3"><div class="kpi dim"><div class="lab">Mail bị trả lại</div><div class="val">—</div></div><div class="kpi dim"><div class="lab">Cần bạn trả lời</div><div class="val">—</div></div><div class="kpi dim"><div class="lab">Cần follow-up</div><div class="val">—</div></div></div></div>`,
        error: `<div class="loaderr"><h2>⚠ Không quét được Gmail</h2><p class="muted">Agent không kết nối được inbox để dựng hàng đợi hôm nay. Last successful scan: hôm qua 08:02.</p><div class="gap"></div><button class="btn">Để sau</button> <button class="btn pri">Quét lại</button></div>`
      }
    },
    s3: {
      states: [
        { id: "draft", label: "draft-ready" },
        { id: "draftGenerating", label: "draft-generating" },
        { id: "needsReply", label: "needs-reply" },
        { id: "confirmClose", label: "confirm-close" },
        { id: "bounced", label: "bounced-alert" },
        { id: "loading", label: "loading" },
        { id: "error", label: "error" },
        { id: "done", label: "done" }
      ],
      html: {
        draft: `<div class="grid2"><div class="card"><span class="pill p-blue">Draft ready · money</span><h2 class="t">Proposal gửi 5 ngày chưa reply</h2><div class="field"><label>To:</label><input value="minh@client***.com" readonly></div><div class="evidence"><b>Tóm tắt hội thoại</b><div class="small muted">Proposal đã gửi 5 ngày trước · khách chưa phản hồi thực chất · deal có giá trị cao · follow-up cadence tới hạn hôm nay.</div><div class="fieldgrid"><div class="fieldbox"><span>waiting_on</span>them</div><div class="fieldbox"><span>confidence</span>high</div><div class="fieldbox"><span>value_type</span>money</div><div class="fieldbox"><span>next_action_hint</span>Duyệt draft</div></div></div><div class="field"><label>Bản nháp follow-up</label><textarea>Chào anh Minh, em gửi lại proposal để anh tiện xem. Nếu anh cần em điều chỉnh phần scope hoặc timeline, anh nhắn em nhé.</textarea></div><button class="btn">Viết lại</button> <button class="btn">Hẹn lại</button> <button class="btn pri">Duyệt và gửi</button><div class="note">Duyệt và gửi bind đúng To + thread. Không tự gửi nếu chưa duyệt.</div></div><div class="card"><h3>Guardrails</h3><div class="step"><span class="mk">✓</span><span class="lb">Đúng người nhận</span><span class="pill p-ok">pass</span></div><div class="step"><span class="mk">✓</span><span class="lb">Không đổi deal terms</span><span class="pill p-ok">pass</span></div><div class="step"><span class="mk">✓</span><span class="lb">Không auto-send</span><span class="pill p-ok">pass</span></div></div></div>`,
        draftGenerating: `<div class="card" style="max-width:760px;margin:24px auto"><h2 class="t">Đang viết lại draft</h2><p class="muted">Nút gửi bị khóa trong lúc draft đang sinh lại để tránh gửi nhầm phiên bản.</p><div class="progbar"><i style="width:64%"></i></div><button class="btn pri" disabled>Duyệt và gửi đang khóa</button> <button class="btn">Hủy viết lại</button></div>`,
        needsReply: `<div class="grid2"><div class="card"><span class="pill p-warn">reply_needs_action</span><h2 class="t">Lan hỏi chiết khấu năm, chưa chốt</h2><div class="field"><label>To:</label><input value="lan@client***.com" readonly></div><div class="evidence"><b>Đối tác hỏi thêm</b><div class="mask">“Bên anh confirm giúp em giá cuối và ngày bắt đầu được không?”</div></div><p class="muted">Đây là ask mới cần anh tự trả lời — agent không soạn hộ reply mới trong v0.</p><button class="btn pri">Mở trong Gmail để trả lời</button> <button class="btn">Hẹn lại</button></div><div class="card"><h3>Outcome</h3><div class="locked">Sau khi anh tự trả lời trong Gmail, Track nền quét thấy user đã reply → thread rời queue và quay lại monitoring.</div></div></div>`,
        confirmClose: `<div class="grid2"><div class="card"><span class="pill p-ok">reply_proposed_close</span><h2 class="t">Đối tác đã xác nhận nhận proposal</h2><div class="evidence"><b>Đối tác đã trả lời</b><div class="mask">“Received, thanks. We will review internally.”</div></div><p class="muted">Agent thấy không có ask mới và đề xuất đóng thread. Cần anh xác nhận trước khi đóng.</p><button class="btn">Chưa phải reply</button> <button class="btn pri">Đóng thread</button></div><div class="card"><h3>Outcome</h3><div class="step"><span class="mk">✓</span><span class="lb">Đóng → closed</span></div><div class="step"><span class="mk">↩</span><span class="lb">Chưa phải reply → monitoring</span></div></div></div>`,
        bounced: `<div class="grid2"><div class="card"><span class="pill p-bad">bounced · pipeline blocked</span><h2 class="t">Proposal gửi cho acme*** bị bounce</h2><div class="field"><label>To:</label><input value="procurement@acme***.con"></div><div class="evidence"><b>Cảnh báo</b><div class="small muted">Mail không tới người nhận. Pipeline đang kẹt trước khi khách thấy proposal.</div></div><button class="btn">Mở Gmail</button> <button class="btn pri">Sửa & gửi lại</button> <button class="btn ghost">Bỏ qua</button></div><div class="card"><h3>NDR signals</h3><div class="miniTable"><div class="between"><span>reason</span><b>domain typo</b></div><div class="between"><span>risk</span><b>deal dead-end</b></div><div class="between"><span>next_action_hint</span><b>fix address</b></div></div></div></div>`,
        loading: `<div class="card" style="max-width:760px;margin:24px auto"><h2 class="t">Đang sinh tóm tắt + bản nháp</h2><div class="progbar"><i style="width:58%"></i></div><div class="step"><span class="mk">✓</span><span class="lb">Đã đọc thread</span></div><div class="step"><span class="mk">◌</span><span class="lb">Đang kiểm tra người nhận + guardrails</span></div></div>`,
        error: `<div class="modalbox"><div class="mh">Không gửi được email <span>⚠️</span></div><div class="mb"><p>Draft chưa gửi được. Người nhận/thread vẫn giữ nguyên, chưa có email nào được gửi.</p></div><div class="mf"><button class="btn">Để sau</button><button class="btn pri">Gửi lại</button></div></div>`,
        done: `<div class="empty"><div class="big">✅</div><b>Đã gửi follow-up</b><div class="muted small">Agent đang theo dõi reply và sẽ đưa thread trở lại queue nếu tới hạn.</div><div class="gap"></div><button class="btn pri">Quay lại Việc cần xử lý</button></div>`
      }
    },
    s4: {
      states: [
        { id: "settings", label: "settings" },
        { id: "memory", label: "memory-suggestions" },
        { id: "deepEvidence", label: "deep-evidence" },
        { id: "empty", label: "empty excludes" },
        { id: "saved", label: "saved" },
        { id: "error", label: "error" }
      ],
      html: {
        settings: `<div class="grid2"><div class="card"><h2 class="t">Nhịp nhắc</h2><div class="field"><label>Ngưỡng ngày</label><select><option>3 ngày</option><option selected>5 ngày</option><option>7 ngày</option></select></div><div class="togglebox"><div><b>Cap số lần nhắc/thread</b><div class="small muted">Không nhắc quá gắt, tránh spam khách.</div></div><span class="sw on"><i></i></span></div><button class="btn pri">Lưu cài đặt</button></div><div class="card"><h2 class="t">Loại trừ</h2><div class="kbrow"><span class="ic">🏷️</span><div class="tx">newsletter@***</div><button class="btn ghost">Xóa</button></div><div class="kbrow"><span class="ic">👤</span><div class="tx">noreply@***</div><button class="btn ghost">Xóa</button></div><button class="btn">Thêm loại trừ</button><div class="gap"></div><h3>Dữ liệu</h3><button class="btn warn">Xóa dữ liệu học giọng</button></div></div>`,
        memory: `<div class="card" style="max-width:960px;margin:auto"><div class="between"><span class="pill p-blue">Risk Profile Draft · B mặc định</span><button class="btn">Xem bằng chứng sâu</button></div><h2 class="t">Em sẽ ưu tiên inbox theo risk profile này</h2><div class="riskGrid"><div class="riskBox"><b>1. Money risk</b><div class="small muted">deal, payment, quote, order.</div></div><div class="riskBox"><b>2. Reputation</b><div class="small muted">lời hứa, deadline, commitment.</div></div><div class="riskBox"><b>3. Meeting</b><div class="small muted">context trước meeting 48h.</div></div><div class="riskBox"><b>4. Relationship</b><div class="small muted">VIP / important contacts.</div></div></div><div class="evidence"><b>Bằng chứng mặc định (mức B) — pattern + subject mask nhẹ</b><div class="mask">12 thread có pattern báo giá/payment · ví dụ: “Re: Proposal for *** project”, “Payment confirmation — *** invoice”</div><div class="mask">7 thread có commitment phrase · ví dụ: “I'll send by Friday — *** deck”, “Follow up on promised ***”</div></div><div class="gap"></div><h3>Đề xuất từ Operating Memory</h3><div class="grid3"><div class="riskBox"><b>Ưu tiên ACME</b><div class="small muted">Nâng priority_tier cho domain ACME.</div><div class="gap"></div><button class="btn soft">Xác nhận</button> <button class="btn ghost">Bỏ qua</button></div><div class="riskBox"><b>Loại trừ digest@***</b><div class="small muted">Hay bị dismiss → gợi ý ExcludeRule.</div><div class="gap"></div><button class="btn soft">Xác nhận</button> <button class="btn ghost">Bỏ qua</button></div><div class="riskBox"><b>Hạ cap thread FYI</b><div class="small muted">Hay soft-close → giảm số lần nhắc.</div><div class="gap"></div><button class="btn soft">Xác nhận</button> <button class="btn ghost">Bỏ qua</button></div></div><div class="gap"></div><button class="btn pri">Xác nhận profile</button> <button class="btn">Sửa ưu tiên</button> <button class="btn">Bỏ qua đề xuất</button></div>`,
        deepEvidence: `<div class="grid2"><div class="card"><h2 class="t">C · Full evidence drill-down</h2><p class="muted">Chỉ mở khi user click “Xem bằng chứng sâu”; KHÔNG show mặc định để tránh cảm giác bị soi quá mức.</p><table><tr><th>Risk</th><th>Thread</th><th>Signal</th></tr><tr><td>Money</td><td>Re: Proposal for ACME rollout</td><td>quote + no reply 5d</td></tr><tr><td>Commitment</td><td>Friday deck promise</td><td>user promised send by date</td></tr><tr><td>Meeting</td><td>Demo prep notes</td><td>meeting in 36h</td></tr></table></div><div class="card"><h3>Privacy stance</h3><div class="locked">B mặc định đủ trust cho skeptical buyer. C chỉ khi click sâu. Operating Memory cập nhật preference/rule, không tự nâng quyền auto-send.</div></div></div>`,
        empty: `<div class="empty"><div class="big">🏷️</div><b>Chưa loại trừ ai</b><div class="muted small">Thêm người hoặc tên miền agent nên bỏ qua.</div><div class="gap"></div><button class="btn pri">Thêm loại trừ</button></div>`,
        saved: `<div class="empty"><div class="big">✅</div><b>Đã lưu Risk Profile</b><div class="muted small">Agent sẽ dùng profile này để ưu tiên queue, nhưng mọi gửi mail vẫn cần anh duyệt.</div></div>`,
        error: `<div class="modalbox"><div class="mh">Không lưu được cài đặt <span>⚠️</span></div><div class="mb"><p>Thay đổi cadence/loại trừ chưa lưu được. Cài đặt hiện tại vẫn giữ nguyên.</p></div><div class="mf"><button class="btn">Để sau</button><button class="btn pri">Lưu lại</button></div></div>`
      }
    }
  }
};
